[workspace]
resolver = "2"
members = ["day01", "day02", "day03", "day04", "day05", "day06", "day07"]

[workspace.lints.clippy]
todo = "warn"
unimplemented = "warn"
dbg_macro = "warn"
unwrap_used = "warn"
expect_used = "warn"